name: Bandit Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Bandit
        uses: PyCQA/bandit-action@v1.0.1
        with:
          path: "."
        continue-on-error: true
